

services:
  mysql:
    image: mysql:8
    container_name: cms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms_db
    ports:
      - "3307:3306"
    restart: always

  app:
    build: .
    container_name: cms-backend
    ports:
      - "8181:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cms_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

